application: 
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /api/feeds.*
  script: api/feeds/reader.py

- url: /
  script: webui/index.py

- url: /
  static_dir: webui/sample/
